### ISSUE TITLE
Support for Symfony 5

### ISSUE THREAD

**Issue by Wirone** [nunomaduro/collision-adapter-symfony#4]
Currently adapter requires Symfony packages with `^4.0` constraint. Please make it compatible with Symfony 5.

**Comment by nunomaduro** [comment]
Can you make a pull request?

**Comment by ostrolucky** [comment]
See https://github.com/nunomaduro/collision-adapter-symfony/pull/5

**Comment by nunomaduro** [comment]
@ostrolucky Added you as maintainer, fell free to release.
